project_id = "blvssrmisvgzesswfewf"

[functions.chat]
verify_jwt = false

[functions.generate-certificate]
verify_jwt = true

[functions.create-webpay-transaction]
verify_jwt = false

[functions.confirm-webpay-transaction]
verify_jwt = false
